export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const CHANGE_PROFILE_DATA = 'CHANGE_PROFILE_DATA';
export const CHANGE_ACCOUNT_DATA = 'CHANGE_ACCOUNT_DATA';
export const SET_SETTING_LOAING = 'SET_SETTING_LOAING';
export const SET_SETTING_PROGGRESS = 'SET_SETTING_PROGGRESS';
